In [10]:
import torch
from torch_scatter import segment_sum_coo, scatter_add

m = torch.tensor([
    [1,2,3,4],
    [5,1,7,8],
    [1,2,3,4],
    [5,2,7,8],
])
m2 = torch.tensor([1,2,3,4])
num_edges = 2
M = torch.zeros(num_edges, 4)
neighbours_id = torch.tensor([0, 1,1,0])
M = segment_sum_coo(m, neighbours_id, dim_size=num_edges)
M2 = scatter_add(m, neighbours_id, dim=0)
M, M2


(tensor([[ 6,  4, 10, 12],
         [ 6,  3, 10, 12]]),
 tensor([[ 6,  4, 10, 12],
         [ 6,  3, 10, 12]]))

In [12]:
m = torch.randn(84, 20)
m

tensor([[-1.5921e+00, -8.7425e-01,  1.3771e+00,  ...,  8.5527e-01,
          2.9093e+00, -4.6996e-01],
        [ 1.3092e+00,  1.3722e+00, -3.7498e-01,  ..., -7.1865e-01,
         -3.8048e-01,  3.0595e-01],
        [-5.1927e-01,  1.9389e-01,  4.5347e-01,  ..., -6.8693e-01,
          7.4255e-01, -7.4074e-01],
        ...,
        [ 6.5004e-02, -1.7380e+00,  1.9732e+00,  ..., -5.9615e-01,
         -1.0426e-01,  3.0060e-03],
        [-6.8694e-01, -1.7107e+00,  9.2123e-01,  ..., -7.4512e-01,
         -6.9263e-02, -4.8492e-05],
        [-5.2986e-01,  3.3781e-01, -3.5487e-02,  ..., -1.3438e+00,
          2.8531e-01, -1.2031e-01]])

In [22]:
id = torch.tensor(
    [0] * 21 + [1] * 21 + [2] * 21 + [3] * 21
)
id

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [28]:
out = scatter_add(m, id, dim=0)
out, out.shape

(tensor([[-4.3014, -2.8717, -7.9633, -2.6829,  2.1359,  2.9311, -6.9749,  0.5228,
           3.0825, -0.9202,  3.8353,  4.9282,  1.0350,  4.9087,  0.8907,  2.7498,
           0.6595, -6.0511,  1.9218, -1.9623],
         [ 1.0718,  8.1395, -0.1450, -9.8817,  1.9251,  6.7179, -5.1759,  0.8303,
           2.7709,  4.3140, -2.4930, -4.5192,  6.6215,  5.4317, -5.9036, -8.1799,
          -0.5017, -1.2716,  2.3459,  1.1630],
         [-0.5160, -2.3502,  2.4410,  8.2419,  0.1245, -0.0914, -4.1413,  6.6617,
          -3.7516,  1.3575,  3.0944,  0.0844,  0.0474,  0.8953, -3.6463, -8.2948,
           0.8873, -4.9363,  6.0158,  2.0046],
         [ 8.8402, -1.4754,  4.7718, -4.3561,  0.6216, -3.8176,  5.8593, -2.6281,
           0.5470,  0.0342,  0.5431,  0.9925,  4.2268,  1.9970, -5.1925,  3.1243,
          -0.4445, -2.0141, -0.4896, 13.1812]]),
 torch.Size([4, 20]))

In [29]:
out = torch.sum(out, dim=0)
out

tensor([  5.0947,   1.4422,  -0.8955,  -8.6788,   4.8070,   5.7400, -10.4328,
          5.3867,   2.6487,   4.7854,   4.9798,   1.4859,  11.9306,  13.2327,
        -13.8517, -10.6005,   0.6006, -14.2732,   9.7940,  14.3864])

In [1]:
import torch

In [3]:
a = torch.randn(10, 3)
b = torch.randn(10, 4)
torch.cat([a,b], dim=1).shape

torch.Size([10, 7])

In [1]:
import torch
from torch.distributions import Categorical

In [8]:
r = torch.Tensor([
    [0.1],
    [0.2],
    [0.4],
    [0.3],
])


In [10]:
r = r.flatten()
dist = Categorical(r)
dist

Categorical(probs: torch.Size([4]))

In [11]:
dist.log_prob(torch.tensor(0))

tensor(-2.3026)

In [14]:
dist.entropy()

tensor(1.2799)

In [15]:
dist.sample()

tensor(2)

In [12]:
a[2] = {'s': 1}
a

[0, 2, {'s': 1}, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [13]:
1 - True

0